# Generated by Django 3.2.5 on 2022-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='work',
            field=models.TextField(),
        ),
    ]
