# Generated by Django 3.2.5 on 2022-01-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todo_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='work',
            new_name='task',
        ),
    ]
